all:
	cd ..; make Consola

base:
	bash BASE.sh

deadlock: 
	bash DEADLOCK.sh

error:
	bash ERROR.sh

memoria:
	bash MEMORIA.sh

fs:
	bash FILESYSTEM.sh

fs2:
	bash FILESYSTEM2.sh

ejemplo: 
	./consola.out codigo.tuki consola.config 

matar:
	./consola.out matar consola.config