all:
	cd ..; make Memoria

base deadlock:
	cp ./tuki-pruebas/BASE.config ./memoria.config; ./memoria.out

error:
	cp ./tuki-pruebas/ERROR.config ./memoria.config; ./memoria.out

best:
	cp ./tuki-pruebas/BEST.config ./memoria.config; ./memoria.out

first:
	cp ./tuki-pruebas/FIRST.config ./memoria.config; ./memoria.out

worst:
	cp ./tuki-pruebas/WORST.config ./memoria.config; ./memoria.out

fs:
	cp ./tuki-pruebas/FILESYSTEM.config ./memoria.config; ./memoria.out

ejemplo:

	cp ./tuki-pruebas/EJEMPLO.config ./memoria.config; ./memoria.out

