all:
	cd ..; make Kernel

fifo:
	cp ./tuki-pruebas/FIFO.config ./kernel.config; ./kernel.out

hrrn:
	cp ./tuki-pruebas/HRRN.config ./kernel.config; ./kernel.out

deadlock:
	cp ./tuki-pruebas/DEADLOCK.config ./kernel.config; ./kernel.out

error:
	cp ./tuki-pruebas/ERROR.config ./kernel.config; ./kernel.out

memoria:
	cp ./tuki-pruebas/MEMORIA.config ./kernel.config; ./kernel.out

fs:
	cp ./tuki-pruebas/FILESYSTEM.config ./kernel.config; ./kernel.out

ejemplo:
	cp ./tuki-pruebas/EJEMPLO.config ./kernel.config; ./kernel.out